# Generated by Django 4.0.2 on 2022-02-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
