# Generated by Django 4.0.2 on 2022-02-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img/product/1.png', upload_to='img/product/'),
        ),
    ]
