# Generated by Django 4.0.2 on 2022-02-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/img/product/1.png', upload_to='static/img/product/'),
        ),
    ]
